[Variables]
bgWidth=600
bgHeight=300
cornerRoundness=3
; Colors
colorBg=15,15,15
colorDialArc=150,150,150
; Font settings
fontFace=IBM Plex Sans
fontFaceCn=IBM Plex Sans Condensed
fontSizeDefault=11
colorTextDefault=230,230,230
; Dial settings
dialRadius=250
dialStartX=3
dialArcThickness=4
dialObjectRadius=10
; Moon settings
moonPhase=0.0
moonRadius=20
moonBorderThickness=2
moonInnerRadius=(#moonRadius# - #moonBorderThickness#)
moonIlluminationAngle=0
showMoonAngle=1
colorMoon=200,200,200
colorBg=15,15,15
colorMoonBg=30,30,30
colorMoonBorder=100,100,100

[StyleString]
FontFace=#fontFace#
FontColor=#colorTextDefault#
FontSize=#fontSizeDefault#
Antialias=1